<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    style="
      margin: auto;
      background: rgba(255, 255, 255, 0) none repeat scroll 0% 0%;
      display: block;
      shape-rendering: auto;
    "
    width="100px"
    height="100px"
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
  >
    <path
      d="M20 25L80 25L80 75L20 75Z"
      fill="#ffffff"
      stroke="#7b68c9"
      stroke-width="3"
    ></path>
    <path
      d="M50 25L80 25L80 75L50 75"
      fill="#ffffff"
      stroke="#7b68c9"
      stroke-width="3"
      stroke-linejoin="round"
      stroke-linecap="round"
    >
      <animate
        attributeName="d"
        dur="0.7692307692307692s"
        repeatCount="indefinite"
        begin="0s"
        keyTimes="0;0.5;0.501;1"
        values="M50 25L80 25L80 75L50 75;M50 25L50 20L50 80L50 75;M50 25L80 25L80 75L50 75;M50 25L80 25L80 75L50 75"
      ></animate>
      <animate
        attributeName="opacity"
        dur="0.7692307692307692s"
        repeatCount="indefinite"
        begin="0s"
        keyTimes="0;0.5;0.5001;1"
        values="1;1;0;0"
      ></animate>
    </path>
    <path
      d="M50 25L80 25L80 75L50 75"
      fill="#ffffff"
      stroke="#7b68c9"
      stroke-width="3"
      stroke-linejoin="round"
      stroke-linecap="round"
    >
      <animate
        attributeName="d"
        dur="0.7692307692307692s"
        repeatCount="indefinite"
        begin="-0.1276923076923077s"
        keyTimes="0;0.5;0.501;1"
        values="M50 25L80 25L80 75L50 75;M50 25L50 20L50 80L50 75;M50 25L80 25L80 75L50 75;M50 25L80 25L80 75L50 75"
      ></animate>
      <animate
        attributeName="opacity"
        dur="0.7692307692307692s"
        repeatCount="indefinite"
        begin="-0.1276923076923077s"
        keyTimes="0;0.5;0.5001;1"
        values="1;1;0;0"
      ></animate>
    </path>
    <path
      d="M50 25L80 25L80 75L50 75"
      fill="#ffffff"
      stroke="#7b68c9"
      stroke-width="3"
      stroke-linejoin="round"
      stroke-linecap="round"
    >
      <animate
        attributeName="d"
        dur="0.7692307692307692s"
        repeatCount="indefinite"
        begin="-0.25384615384615383s"
        keyTimes="0;0.5;0.501;1"
        values="M50 25L80 25L80 75L50 75;M50 25L50 20L50 80L50 75;M50 25L80 25L80 75L50 75;M50 25L80 25L80 75L50 75"
      ></animate>
      <animate
        attributeName="opacity"
        dur="0.7692307692307692s"
        repeatCount="indefinite"
        begin="-0.25384615384615383s"
        keyTimes="0;0.5;0.5001;1"
        values="1;1;0;0"
      ></animate>
    </path>
    <path
      d="M50 25L80 25L80 75L50 75"
      fill="#ffffff"
      stroke="#7b68c9"
      stroke-width="3"
      stroke-linejoin="round"
      stroke-linecap="round"
    >
      <animate
        attributeName="d"
        dur="0.7692307692307692s"
        repeatCount="indefinite"
        begin="-0.25384615384615383s"
        keyTimes="0;0.499;0.5;1"
        values="M50 25L20 25L20 75L50 75;M50 25L20 25L20 75L50 75;M50 25L50 20L50 80L50 75;M50 25L20 25L20 75L50 75"
      ></animate>
      <animate
        attributeName="opacity"
        dur="0.7692307692307692s"
        repeatCount="indefinite"
        begin="-0.25384615384615383s"
        keyTimes="0;0.4999;0.5;1"
        values="0;0;1;1"
      ></animate>
    </path>
    <path
      d="M50 25L80 25L80 75L50 75"
      fill="#ffffff"
      stroke="#7b68c9"
      stroke-width="3"
      stroke-linejoin="round"
      stroke-linecap="round"
    >
      <animate
        attributeName="d"
        dur="0.7692307692307692s"
        repeatCount="indefinite"
        begin="-0.1276923076923077s"
        keyTimes="0;0.499;0.5;1"
        values="M50 25L20 25L20 75L50 75;M50 25L20 25L20 75L50 75;M50 25L50 20L50 80L50 75;M50 25L20 25L20 75L50 75"
      ></animate>
      <animate
        attributeName="opacity"
        dur="0.7692307692307692s"
        repeatCount="indefinite"
        begin="-0.1276923076923077s"
        keyTimes="0;0.4999;0.5;1"
        values="0;0;1;1"
      ></animate>
    </path>
    <path
      d="M50 25L80 25L80 75L50 75"
      fill="#ffffff"
      stroke="#7b68c9"
      stroke-width="3"
      stroke-linejoin="round"
      stroke-linecap="round"
    >
      <animate
        attributeName="d"
        dur="0.7692307692307692s"
        repeatCount="indefinite"
        begin="0s"
        keyTimes="0;0.499;0.5;1"
        values="M50 25L20 25L20 75L50 75;M50 25L20 25L20 75L50 75;M50 25L50 20L50 80L50 75;M50 25L20 25L20 75L50 75"
      ></animate>
      <animate
        attributeName="opacity"
        dur="0.7692307692307692s"
        repeatCount="indefinite"
        begin="0s"
        keyTimes="0;0.4999;0.5;1"
        values="0;0;1;1"
      ></animate>
    </path>
    <!-- [ldio] generated by https://loading.io/ -->
  </svg>
</template>

<script>
export default {};
</script>

<style></style>
